version: '3.9'
services:
  backend:
    container_name: backend
    build: ./api-server
    tty: true
    depends_on:
      - db
    volumes:
      - ./api-server:/backend
      - /etc/localtime:/etc/localtime:ro # タイムゾーンを日本時刻に設定
    environment:
      TZ: Asia/Tokyo # タイムゾーンを日本時刻に設定
    ports:
      - 8080:3000
    security_opt:
      - seccomp:unconfined
  db:
    container_name: db
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    env_file:
      - ./mysql/mysql.env
    volumes:
      - nest_todo_graphql_data:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3306:3306
volumes:
  nest_todo_graphql_data:
